version: "3.9"
services:
  api:
    build: .
    container_name: express_api
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      # コンテナ間はサービス名で到達できるので「http://dynamodb:8000」
      - DDB_ENDPOINT=http://dynamodb:8000
      - AWS_REGION=ap-northeast-1
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
    depends_on:
      - dynamodb

  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb_local
    ports:
      - "8000:8000" # 任意：ホストからも確認したければ公開
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]
    # 永続化したい場合は上の "-inMemory" を外して volume を付ける:
    # volumes:
    #   - ./ddb_data:/home/dynamodblocal/data
    # command: ["-jar","DynamoDBLocal.jar","-sharedDb","-dbPath","/home/dynamodblocal/data"]

  # 任意：GUI（ブラウザで中身を見たい場合）
  # dynamodb_admin:
  #   image: aaronshaf/dynamodb-admin
  #   ports:
  #     - "8001:8001"
  #   environment:
  #     - DYNAMO_ENDPOINT=http://dynamodb:8000
  #   depends_on:
  #     - dynamodb
